1. --with-functions's option 2. this func usage message
1. --with-functions's build option 
2. this function's usage message
both are intended for mac os x. 

o Error log
brew install --with-json1 --with-functions  sqlite3
==> Downloading https://sqlite.org/2018/sqlite-autoconf-3240000.tar.gz
Already downloaded: /home/username/.cache/Homebrew/sqlite-3.24.0.tar.gz
==> ./configure --prefix=/home/username/.linuxbrew/Cellar/sqlite/3.24.0 --enable-dynamic-extensions --enable-readlin
==> make install
==> Downloading https://sqlite.org/contrib/download/extension-functions.c?get=25
Already downloaded: /home/username/.cache/Homebrew/sqlite--functions-2010-02-06.c
==> gcc-5 -fno-common -dynamiclib extension-functions.c -o libsqlitefunctions.dylib
Last 15 lines from /home/username/.cache/Homebrew/Logs/sqlite/03.gcc-5:
/tmp/ccyR6mig.o: In function `log10Func':
extension-functions.c:(.text+0x1630): undefined reference to `log10'
/tmp/ccyR6mig.o: In function `expFunc':
extension-functions.c:(.text+0x1763): undefined reference to `exp'
/tmp/ccyR6mig.o: In function `powerFunc':
extension-functions.c:(.text+0x1cf8): undefined reference to `pow'
/tmp/ccyR6mig.o: In function `atn2Func':
extension-functions.c:(.text+0x1e85): undefined reference to `atan2'
/tmp/ccyR6mig.o: In function `ceilFunc':
extension-functions.c:(.text+0x2109): undefined reference to `ceil'
/tmp/ccyR6mig.o: In function `floorFunc':
extension-functions.c:(.text+0x2227): undefined reference to `floor'
/tmp/ccyR6mig.o: In function `stdevFinalize':
extension-functions.c:(.text+0x4154): undefined reference to `sqrt'
collect2: error: ld returned 1 exit status

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

o After
brew reinstall --with-json1 --with-functions --with-secure-delete sqlite3
==> Reinstalling sqlite --with-secure-delete --with-functions --with-json1
==> Downloading https://sqlite.org/2018/sqlite-autoconf-3240000.tar.gz
Already downloaded: /home/username/.cache/Homebrew/sqlite-3.24.0.tar.gz
==> ./configure --prefix=/home/username/.linuxbrew/Cellar/sqlite/3.24.0 --enable-dynamic-extensions --enab
==> make install
==> Downloading https://sqlite.org/contrib/download/extension-functions.c?get=25
Already downloaded: /home/username/.cache/Homebrew/sqlite--functions-2010-02-06.c
==> gcc-5 -fPIC -lm -shared extension-functions.c -o libsqlitefunctions.so
==> Caveats
Usage instructions for applications calling the sqlite3 API functions:

  In your application, call sqlite3_enable_load_extension(db,1) to
  allow loading external libraries.  Then load the library libsqlitefunctions
  using sqlite3_load_extension; the third argument should be 0.
  See https://sqlite.org/loadext.html.
  Select statements may now use these functions, as in
  SELECT cos(radians(inclination)) FROM satsum WHERE satnum = 25544;

Usage instructions for the sqlite3 program:

  If the program is built so that loading extensions is permitted,
  the following will work:
   sqlite> SELECT load_extension('/home/username/.linuxbrew/opt/sqlite/lib/libsqlitefunctions');
   sqlite> select cos(radians(45));
   0.707106781186548
==> Summary
🍺  /home/username/.linuxbrew/Cellar/sqlite/3.24.0: 13 files, 23.8MB, built in